"use client";

import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { Loader2, Search, Copy, Check, FlaskConical, HardDrive, Globe, Users } from "lucide-react";
import { analyzeModel, getHardwarePresets, getShare } from "@/lib/api";
import type { ModelAnalysis, HardwareProfile, HardwarePreset } from "@/lib/types";
import ModelInfoCard from "@/components/ModelInfoCard";
import BenchmarkChart from "@/components/BenchmarkChart";
import CapabilityRadar from "@/components/CapabilityRadar";
import QuantLadder from "@/components/QuantLadder";
import HardwareWizard from "@/components/HardwareWizard";
import ModelVariantPicker from "@/components/ModelVariantPicker";
import ShareButton from "@/components/ShareButton";
import LocalFileAnalyzer from "@/components/LocalFileAnalyzer";
import NewPostModal from "@/components/NewPostModal";
import ExportButton from "@/components/ExportButton";
import { cn } from "@/lib/utils";
import { formatParams, formatCtx } from "@/lib/utils";

const DEFAULT_HW: HardwareProfile = {
  cpu_name: "Generic CPU",
  cpu_threads: 8,
  ram_gb: 16,
  cpu_memory_bandwidth_gbps: 50,
};

const FRAMEWORKS = ["llama.cpp", "ollama", "lmstudio", "transformers", "vllm", "mlx"];

export default function AnalyzePage() {
  const params = useSearchParams();
  const [repoId, setRepoId] = useState(params?.get("repo") || "");
  const [hardware, setHardware] = useState<HardwareProfile>(DEFAULT_HW);
  const [presets, setPresets] = useState<HardwarePreset[]>([]);
  const [framework, setFramework] = useState("llama.cpp");
  const [contextLength, setContextLength] = useState(8192);
  const [useWolfram, setUseWolfram] = useState(false);
  const [result, setResult] = useState<ModelAnalysis | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [sourceTab, setSourceTab] = useState<"hf" | "local">("hf");
  const [showShare, setShowShare] = useState(false);

  useEffect(() => {
    getHardwarePresets().then(setPresets).catch(() => {});
    const shareId = params?.get("share");
    if (shareId) {
      getShare(shareId).then((s) => {
        const p = s.params as Record<string, unknown>;
        if (p.repo_id) setRepoId(String(p.repo_id));
        if (p.hardware) setHardware(p.hardware as HardwareProfile);
      }).catch(() => {});
    }
  }, []);

  const shareParams = result
    ? { repo_id: repoId, hardware, context_length: contextLength, framework }
    : null;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!repoId.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const r = await analyzeModel({
        repo_id: repoId.trim(),
        hardware_profile: hardware,
        context_length: contextLength,
        framework,
        use_wolfram: useWolfram,
      });
      setResult(r);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Analysis failed");
    } finally {
      setLoading(false);
    }
  }

  async function copyEmbedCode() {
    if (!result) return;
    const md = [
      `## OpenBench Analysis`,
      ``,
      `| Field | Value |`,
      `|---|---|`,
      `| Params | ${formatParams(result.parameter_count)} |`,
      `| Context | ${formatCtx(result.context_length)} |`,
      `| Architecture | ${result.architecture} |`,
      `| Quantization | ${result.quantization} (${result.bits_per_weight} bpw) |`,
      `| Memory needed | ${result.memory_estimate?.total_gb.toFixed(1)} GB |`,
      `| CPU speed est. | ${result.speed_estimate?.cpu_tps_min.toFixed(1)}–${result.speed_estimate?.cpu_tps_max.toFixed(1)} t/s |`,
      ``,
      `*Generated by [OpenBench](https://github.com/)*`,
    ].join("\n");
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-bench-text mb-1 flex items-center gap-2">
          <Search size={28} className="text-bench-accent" />
          Analyze Model
        </h1>
        <p className="text-bench-muted text-sm">
          Deep analysis of a single model — GGUF variants, memory, speed, and benchmarks
        </p>
      </div>

      {/* Source tabs */}
      <div className="flex gap-1 bg-bench-card rounded-xl border border-bench-border p-1 mb-4 w-fit">
        <button
          onClick={() => setSourceTab("hf")}
          className={cn(
            "flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium transition-all",
            sourceTab === "hf" ? "bg-bench-accent text-white" : "text-bench-muted hover:text-bench-text"
          )}
        >
          <Globe size={14} /> Hugging Face
        </button>
        <button
          onClick={() => setSourceTab("local")}
          className={cn(
            "flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium transition-all",
            sourceTab === "local" ? "bg-bench-accent text-white" : "text-bench-muted hover:text-bench-text"
          )}
        >
          <HardDrive size={14} /> Local File
        </button>
      </div>

      {/* Local file analyzer */}
      {sourceTab === "local" && (
        <div className="rounded-2xl border border-bench-border bg-bench-card p-5 mb-6 space-y-4">
          <div>
            <label className="text-xs text-bench-muted mb-1.5 block">Your Hardware</label>
            <HardwareWizard value={hardware} presets={presets} onChange={setHardware} />
          </div>
          <LocalFileAnalyzer
            hardware={hardware}
            onResult={(r) => { setResult(r); setError(null); }}
          />
        </div>
      )}

      {/* Form */}
      {sourceTab === "hf" && (
      <form onSubmit={handleSubmit} className="rounded-2xl border border-bench-border bg-bench-card p-5 mb-6 space-y-4">
        <div>
          <label className="text-xs text-bench-muted mb-1.5 block">HuggingFace Repo ID</label>
          <input
            value={repoId}
            onChange={(e) => setRepoId(e.target.value)}
            placeholder="bartowski/Meta-Llama-3.1-8B-Instruct-GGUF"
            className="w-full px-4 py-2.5 rounded-xl bg-bench-surface border border-bench-border text-bench-text placeholder-bench-muted/50 focus:outline-none focus:border-bench-accent text-sm"
          />
        </div>

        {repoId.includes("/") && (
          <ModelVariantPicker
            repoId={repoId}
            ramGb={hardware.vram_gb || hardware.ram_gb}
          />
        )}

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          <div className="sm:col-span-2">
            <label className="text-xs text-bench-muted mb-1.5 block">Your Hardware</label>
            <HardwareWizard value={hardware} presets={presets} onChange={setHardware} />
          </div>

          <div>
            <label className="text-xs text-bench-muted mb-1.5 block">Framework</label>
            <select
              value={framework}
              onChange={(e) => setFramework(e.target.value)}
              className="w-full px-3 py-2.5 rounded-xl bg-bench-surface border border-bench-border text-bench-text text-sm focus:outline-none focus:border-bench-accent"
            >
              {FRAMEWORKS.map((f) => (
                <option key={f} value={f}>{f}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="text-xs text-bench-muted mb-1.5 block">Context (tokens)</label>
            <input
              type="number"
              value={contextLength}
              onChange={(e) => setContextLength(Number(e.target.value))}
              step={1024}
              min={512}
              className="w-full px-3 py-2.5 rounded-xl bg-bench-surface border border-bench-border text-bench-text text-sm focus:outline-none focus:border-bench-accent"
            />
          </div>
        </div>

        <div className="flex items-center justify-between gap-4">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={useWolfram}
              onChange={(e) => setUseWolfram(e.target.checked)}
              className="w-4 h-4 rounded accent-indigo-500"
            />
            <span className="text-sm text-bench-muted flex items-center gap-1">
              <FlaskConical size={13} />
              Wolfram symbolic derivation
            </span>
          </label>

          <button
            type="submit"
            disabled={loading || !repoId.trim()}
            className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-bench-accent hover:bg-indigo-500 disabled:opacity-40 text-white font-semibold text-sm transition-all"
          >
            {loading ? <Loader2 size={15} className="animate-spin" /> : <Search size={15} />}
            {loading ? "Analyzing…" : "Analyze"}
          </button>
        </div>
      </form>
      )}

      {error && (
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 text-red-400 px-4 py-3 text-sm mb-6">
          {error}
        </div>
      )}

      {loading && (
        <div className="flex flex-col items-center gap-3 py-20 text-bench-muted">
          <Loader2 size={32} className="animate-spin text-bench-accent" />
          <p>Fetching GGUF header and model metadata…</p>
          <p className="text-xs">Large repos may take up to 30s for the first analysis</p>
        </div>
      )}

      {result && !loading && (
        <div id="analyze-export-root" className="space-y-6 animate-fade-in">
          {/* Header + export */}
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-2xl font-bold text-bench-text">{result.name}</h2>
              <p className="text-bench-muted text-sm">{result.repo_id}</p>
            </div>
            <div className="flex items-center gap-2 shrink-0 flex-wrap justify-end">
              <ExportButton
                targetId="analyze-export-root"
                filename={`openbench-${result.repo_id.replace(/\//g, "-")}`}
              />
              <button
                onClick={() => setShowShare(true)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-bench-surface border border-bench-border text-bench-muted hover:text-emerald-400 hover:border-emerald-500/40 transition-all text-sm"
              >
                <Users size={14} /> Share to Community
              </button>
              {shareParams && (
                <ShareButton type="analyze" params={shareParams as Record<string, unknown>} />
              )}
              <button
                onClick={copyEmbedCode}
                className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-bench-surface border border-bench-border text-bench-muted hover:text-bench-text transition-all text-sm"
              >
                {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                {copied ? "Copied!" : "Copy embed"}
              </button>
            </div>
          </div>

          <ModelInfoCard model={result} />

          {result.gguf_variants.length > 0 && (
            <div className="rounded-2xl border border-bench-border bg-bench-card p-5">
              <h3 className="font-semibold text-bench-text mb-4">
                Quantization Ladder — {result.gguf_variants.length} variants
              </h3>
              <QuantLadder
                variants={result.gguf_variants}
                availableGb={hardware.vram_gb || hardware.ram_gb}
              />
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            <div className="rounded-2xl border border-bench-border bg-bench-card p-5">
              <BenchmarkChart modelA={result} />
            </div>
            <div className="rounded-2xl border border-bench-border bg-bench-card p-5">
              <CapabilityRadar modelA={result} />
            </div>
          </div>

          {/* Wolfram derivation */}
          {result.wolfram_derivation && (
            <div className="rounded-2xl border border-violet-500/30 bg-violet-500/10 p-5">
              <h3 className="font-semibold text-violet-400 mb-3 flex items-center gap-2">
                <FlaskConical size={16} />
                Wolfram Memory Derivation
              </h3>
              <pre className="text-bench-muted text-xs font-mono leading-relaxed whitespace-pre-wrap">
                {result.wolfram_derivation}
              </pre>
            </div>
          )}
        </div>
      )}
      {showShare && result && (
        <NewPostModal
          onClose={() => setShowShare(false)}
          onCreated={() => setShowShare(false)}
          prefill={{
            title: `Analysis: ${result.name}`,
            body: `Architecture: ${result.architecture}, ${result.parameter_count > 0 ? Math.round(result.parameter_count / 1e9) + "B params" : ""}, ${result.quantization} quant.\nMemory: ${result.memory_estimate?.total_gb.toFixed(1)} GB\nCPU speed: ${result.speed_estimate?.cpu_tps_min.toFixed(0)}–${result.speed_estimate?.cpu_tps_max.toFixed(0)} t/s`,
            post_type: "experiment",
            model_repo: result.repo_id.startsWith("local/") ? result.repo_id.replace("local/", "") : result.repo_id,
            is_local: result.repo_id.startsWith("local/"),
            result_data: result as unknown as Record<string, unknown>,
            tags: ["gguf", result.architecture !== "unknown" ? result.architecture : ""].filter(Boolean),
          }}
        />
      )}
    </div>
  );
}
